### ISSUE TITLE
Build source distribution Python CI job is failing November 2023

### ISSUE THREAD

**Issue by traversaro** [robotology/ycm-cmake-modules#437]
~~~
running egg_info
creating ycm_cmake_modules.egg-info
writing ycm_cmake_modules.egg-info/PKG-INFO
writing dependency_links to ycm_cmake_modules.egg-info/dependency_links.txt
writing top-level names to ycm_cmake_modules.egg-info/top_level.txt
writing manifest file 'ycm_cmake_modules.egg-info/SOURCES.txt'
writing manifest file 'ycm_cmake_modules.egg-info/SOURCES.txt'
/tmp/build-env-nbtnlr5u/lib/python3.8/site-packages/setuptools/config/expand.py:134: SetuptoolsWarning: File '/home/runner/work/ycm/ycm/tools/pip/README.md; charset=UTF-8' cannot be found
  return '\n'.join(
/tmp/build-env-nbtnlr5u/lib/python3.8/site-packages/setuptools/config/expand.py:134: SetuptoolsWarning: File '/home/runner/work/ycm/ycm/tools/pip/README.md; charset=UTF-8' cannot be found
  return '\n'.join(
* Building sdist...
running sdist
running egg_info
writing ycm_cmake_modules.egg-info/PKG-INFO
writing dependency_links to ycm_cmake_modules.egg-info/dependency_links.txt
writing top-level names to ycm_cmake_modules.egg-info/top_level.txt
writing manifest file 'ycm_cmake_modules.egg-info/SOURCES.txt'
running check
/tmp/build-env-nbtnlr5u/lib/python3.8/site-packages/setuptools/config/expand.py:134: SetuptoolsWarning: File '/home/runner/work/ycm/ycm/tools/pip/README.md; charset=UTF-8' cannot be found
  return '\n'.join(
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 304, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
  File "/tmp/build-env-nbtnlr5u/lib/python3.8/site-packages/setuptools/build_meta.py", line 439, in build_sdist
    return self._build_with_temp_dir(
  File "/tmp/build-env-nbtnlr5u/lib/python3.8/site-packages/setuptools/build_meta.py", line 419, in _build_with_temp_dir
    self.run_setup()
  File "/tmp/build-env-nbtnlr5u/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in run_setup
    exec(code, locals())
  File "<string>", line 20, in <module>
  File "/tmp/build-env-nbtnlr5u/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/tmp/build-env-nbtnlr5u/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/tmp/build-env-nbtnlr5u/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/tmp/build-env-nbtnlr5u/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/tmp/build-env-nbtnlr5u/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/tmp/build-env-nbtnlr5u/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/tmp/build-env-nbtnlr5u/lib/python3.8/site-packages/setuptools/command/sdist.py", line 65, in run
    self.make_distribution()
  File "/tmp/build-env-nbtnlr5u/lib/python3.8/site-packages/setuptools/command/sdist.py", line 89, in make_distribution
    orig.sdist.make_distribution(self)
  File "/tmp/build-env-nbtnlr5u/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 508, in make_distribution
    self.make_release_tree(base_dir, self.filelist.files)
  File "/tmp/build-env-nbtnlr5u/lib/python3.8/site-packages/cmake_build_extension/sdist_command.py", line 36, in make_release_tree
    setuptools_scm.integration.Configuration.from_file(
AttributeError: module 'setuptools_scm.integration' has no attribute 'Configuration'

ERROR Backend subprocess exited when trying to invoke build_sdist
Error: Process completed with exit code 1.
~~~

**Comment by traversaro** [comment]
Due to this error, I disabled the python workflow in https://github.com/robotology/ycm/actions/workflows/python.yml . Interested users are welcome to provide a PR to fix the CI and restore the Python workflow.

**Comment by traversaro** [comment]
fyi @diegoferigo, I realized I never mentioned you here.

**Comment by diegoferigo** [comment]
Thanks @traversaro for the ping. Can you please try to rebuild it again? It seems similar to https://github.com/artivis/manif/issues/306, that got solved by a system update. Maybe there was a bug introduced in `setuptools` that got solved.

**Comment by traversaro** [comment]
> Thanks @traversaro for the ping. Can you please try to rebuild it again? It seems similar to [artivis/manif#306](https://github.com/artivis/manif/issues/306), that got solved by a system update. Maybe there was a bug introduced in `setuptools` that got solved.

Output in https://github.com/robotology/ycm-cmake-modules/pull/460#issuecomment-2328395101 .

**Comment by traversaro** [comment]
I disabled the CI steps again as they are a bit noisy otherwise.

**Comment by traversaro** [comment]
It does not seem to be interest from users to be able to install ycm from pip. In particular if you are using ycm in a CMake project and you want to build the CMake via pip, probably it is just a good idea to simply use FetchContent to get YCM, see https://github.com/robotology/ycm-cmake-modules/pull/463, so I think we can simply close this as not planned.
